# -*- coding: utf-8 -*-
"""pull_and_write_json(RileyAssignment).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1azN-XU69_-fbD9vOWKNVTaOyy8rKwpPm
"""

import pandas as pd
import json

# import urllib library
from urllib.request import urlopen
  
# import json
import json
# store the URL in url as 
# parameter for urlopen
url = "https://eservices.mas.gov.sg/api/action/datastore/search.json?resource_id=95932927-c8bc-4e7a-b484-68a66a24edfe&limit=100&sort=end_of_day%20desc"
  
# store the response of URL
response = urlopen(url)
  
# storing the JSON response 
# from url in data
data_json = json.loads(response.read())

data = (data_json['result']['records'])

currency_df = pd.DataFrame.from_dict(data)

currency_df.iloc[1]

result_by_day = {}

for date_info in data:
    date = date_info['end_of_day']
    rate= []
    atribute = list(date_info.keys())    
    atribute.remove('preliminary')
    atribute.remove('timestamp')
    atribute.remove('end_of_day')
    record = {}
    for rate_name in atribute: 
            record[rate_name] = date_info[rate_name]
    result_by_day[date] = record

result_by_day['2023-05-26']

with open("json/resultByDay.json", "w") as outfile:
    json.dump(result_by_day, outfile)